language: python

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -v tests/tests.py

notifications:
  email:
    recipients:
      - jullyanne.motta@gmail.com
    on_success: always
    on_failure: always
