language: python

rvm:
  - 1.9.3

addons:
  sonarcloud:
    organization: jullyannem-github
    token:
      secure: "$SONARCLOUD_TOKEN"

before_install:
  - rvm install 1.9.3
  - travis_internal_ruby() { echo "1.9.3"; }

install:
- pip install -r requirements.txt
- gem install dpl

stages:
- name: Test & QA
- name: Deploy

jobs:
  include:
  - stage: Test & QA
    script:
    - python -m pytest -v tests/tests.py
    - sonar-scanner

  - stage: Deploy
    script: skip
    deploy:
      provider: openshift
      skip_cleanup: true
      user: $OCP_USER
      password:
        secure: $OCP_PASSWORD
      app: cicd-app
      domain: cicd-app
      on:
        repo: JullyAnneM/cicd-app
        branch: master

notifications:
  email:
    recipients:
    - mail@gmail.com
    on_success: change
    on_failure: always
