language: python

install:
  - pip install -r requirements.txt


jobs:
  include:
    - stage: "Test"
      script:
      - python -m pytest -v tests/tests.py

notifications:
  email:
    recipients:
      - jullyanne.motta@gmail.com
    on_success: always
    on_failure: always
