language: python

addons:
  sonarcloud:
    organization: jullyannem-github
    token:
      secure: "$SONARCLOUD_TOKEN"

install:
- pip install -r requirements.txt

stages:
- name: Test & QA
- name: Deploy

jobs:
  include:
  - stage: Test & QA
    script:
    - python -m pytest -v tests/tests.py
    - sonar-scanner

  - stage: Deploy
    script: skip
    deploy:
      provider: openshift
      user: $OCP_USER
      password:
        secure: $OCP_PASSWORD
      app: cicd-app
      domain: https://openshift.sharedocp39.lab.rdu2.cee.redhat.com
      on:
        repo: JullyAnneM/cicd-app
        branch: master

notifications:
  email:
    recipients:
    - jullyanne.motta@gmail.com
    on_success: change
    on_failure: always
